sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t jelnab/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true jelnab/docker-react npm run test